[package]
name = "surrealist"
version = "0.0.0"
description = "Powerful graphical SurrealDB query playground and database explorer for Browser and Desktop"
authors = ["Starlane Studios"]
license = "MIT"
repository = "https://github.com/StarlaneStudios/Surrealist"
edition = "2021"
publish = false

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
tauri = { version = "1.4.1", features = ["devtools", "dialog-save", "fs-write-file", "shell-open", "window-set-always-on-top", "window-set-title", "window-show"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
