name: Publish Surrealist

on:
  workflow_dispatch:
  push:
    branches:
      - release

permissions: write-all

jobs:
  package:
    name: Package
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18 ] 
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

      - name: Frontend dependencies
        run: |
          npm i -g pnpm
          pnpm install
      
      - name: Build application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseDraft: true

      - name: Upload web app (Linux)
        uses: actions/upload-pages-artifact@v1
        if: matrix.platform == 'ubuntu-latest'
        with:
          path: ./dist
  
      - name: Publish web app (Linux)
        uses: actions/deploy-pages@v1
        id: deployment