name: Publish Surrealist

on:
  workflow_dispatch:
  push:
    branches:
      - release

permissions: write-all

jobs:
  version:
    name: Extract version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.2.1

  package:
    name: Package
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18 ] 
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    needs: version
    steps:
      - name: Information
        run: echo "Building Surrealist version ${{ needs.version.outputs.version }} for ${{ matrix.platform }}"
        
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

      - name: Frontend dependencies
        run: |
          npm i -g pnpm
          pnpm install

      - name: Build application
        run: pnpm tauri build

      - name: Upload web app
        uses: actions/upload-pages-artifact@v1
        if: matrix.platform == 'ubuntu-latest'
        with:
          path: ./dist

      - name: Upload bundles
        uses: actions/upload-artifact@v2
        with:
          name: bundles-${{ matrix.platform }}
          path: ./src-tauri/target/release/bundle
  release:
    runs-on: ubuntu-latest
    needs:
      - version
      - package
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Debug
        run: |
          sudo apt install tree
          tree
          ls

      # - name: Rename binary (Windows)
      #   run: |
      #     mv ./surrealist.exe ./surrealist-${{ github.ref_name }}-windows-amd64.exe
      #     mv ./surrealist-linux.tgz ./surrealist-${{ github.ref_name }}-linux-amd64.tgz
      #     mv ./surrealist-amd.tgz ./surrealist-${{ github.ref_name }}-darwin-amd64.tgz
      #     mv ./surrealist-arm.tgz ./surrealist-${{ github.ref_name }}-darwin-arm64.tgz

      # - name: Draft release
      #   uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "v$VERSION"
      #     prerelease: false
      #     draft: true
      #     title: "${{ github.ref_name }}"
      #     files: |
      #       ./surrealist-${{ github.ref_name }}-windows-amd64.exe
      #       ./surrealist-${{ github.ref_name }}-linux-amd64.tgz
      #       ./surrealist-${{ github.ref_name }}-darwin-amd64.tgz
      #       ./surrealist-${{ github.ref_name }}-darwin-arm64.tgz
      
      # - name: Publish web app (Linux)
      #   uses: actions/deploy-pages@v1
      #   id: deployment